package app.humanrouter.routing

import org.json.JSONObject
import java.io.File
import java.util.PriorityQueue
import kotlin.math.PI
import kotlin.math.asin
import kotlin.math.ceil
import kotlin.math.cos
import kotlin.math.min
import kotlin.math.sin
import kotlin.math.sqrt

/**
 * Static rail router over the route graph generated into runtime-v0.5.0.
 *
 * The ordered stop sequence and total route duration come from OSM route relations. Segment
 * durations are constrained estimates generated by the runtime builder. METRO and MCC are enabled;
 * MCD remains disabled here until a real departure/headway feed is added, so we do not invent a
 * commuter-train wait time.
 */
internal class RailGraphRouter private constructor(
    private val preferences: RoutePreferences,
    private val walkGraph: RuntimeWalkGraph?,
    graphFile: File
) {
    private data class Node(
        val index: Int,
        val osmId: String,
        val name: String,
        val point: GeoPoint
    )

    private data class Edge(
        val from: Int,
        val to: Int,
        val seconds: Int,
        val routeId: String,
        val lineKey: String,
        val lineName: String,
        val mode: TransportMode,
        val confidence: Double
    )

    private data class State(
        val node: Int,
        val lineKey: String?,
        val insideSystem: Boolean
    )

    private data class QueueItem(val state: State, val seconds: Int)

    private sealed interface Previous {
        data class Access(val walk: RuntimeWalkGraph.WalkCost) : Previous
        data class Ride(val previous: State, val edge: Edge, val extraBeforeSeconds: Int) : Previous
        data class Transfer(val previous: State, val seconds: Int) : Previous
    }

    private data class Access(val node: Int, val cost: RuntimeWalkGraph.WalkCost)
    private data class Terminal(val state: State, val totalSeconds: Int, val egress: RuntimeWalkGraph.WalkCost)

    private val nodes = ArrayList<Node>()
    private val nodeIndexByOsmId = HashMap<String, Int>()
    private val adjacency = ArrayList<MutableList<Edge>>()
    private val groupsByName = HashMap<String, MutableList<Int>>()
    private val modesByNode = HashMap<Int, MutableSet<TransportMode>>()
    private val linesByNode = HashMap<Int, MutableSet<String>>()

    init {
        load(JSONObject(graphFile.readText()))
    }

    fun findFastest(
        origin: GeoPoint,
        destination: GeoPoint,
        departureEpochSec: Long,
        originName: String = "Откуда",
        destinationName: String = "Куда"
    ): RouteCandidate? {
        if (nodes.isEmpty()) return null
        val access = walkingLinks(origin, towardDestination = false)
        val egress = walkingLinks(destination, towardDestination = true).associateBy { it.node }
        if (access.isEmpty() || egress.isEmpty()) return null

        val distance = HashMap<State, Int>(2_048)
        val previous = HashMap<State, Previous>(2_048)
        val queue = PriorityQueue(compareBy<QueueItem> { it.seconds })

        for (link in access) {
            val state = State(link.node, null, false)
            val old = distance[state]
            if (old == null || link.cost.seconds < old) {
                distance[state] = link.cost.seconds
                previous[state] = Previous.Access(link.cost)
                queue += QueueItem(state, link.cost.seconds)
            }
        }

        var best: Terminal? = null
        while (queue.isNotEmpty()) {
            val item = queue.remove()
            if (distance[item.state] != item.seconds) continue
            val currentBest = best
            if (currentBest != null && item.seconds >= currentBest.totalSeconds) break

            egress[item.state.node]?.let { out ->
                val exitSeconds = if (item.state.insideSystem) exitSeconds(nodeMode(item.state.node)) else 0
                val total = item.seconds + exitSeconds + out.cost.seconds
                if (currentBest == null || total < currentBest.totalSeconds) {
                    best = Terminal(item.state, total, out.cost.copy(seconds = out.cost.seconds + exitSeconds))
                }
            }

            for (edge in adjacency[item.state.node]) {
                val extra = when {
                    item.state.lineKey == edge.lineKey -> 0
                    item.state.lineKey == null && !item.state.insideSystem -> entranceSeconds(edge.mode) + expectedWaitSeconds(edge.mode)
                    item.state.lineKey == null -> expectedWaitSeconds(edge.mode)
                    else -> SAME_PLATFORM_CHANGE_SECONDS + expectedWaitSeconds(edge.mode)
                }
                val next = State(edge.to, edge.lineKey, true)
                val candidate = item.seconds + extra + edge.seconds
                relax(next, candidate, Previous.Ride(item.state, edge, extra), distance, previous, queue)
            }

            if (item.state.insideSystem) {
                val group = groupsByName[normalizeName(nodes[item.state.node].name)].orEmpty()
                for (other in group) {
                    if (other == item.state.node) continue
                    val transfer = transferSeconds(item.state.node, other)
                    val next = State(other, null, true)
                    val candidate = item.seconds + transfer
                    relax(next, candidate, Previous.Transfer(item.state, transfer), distance, previous, queue)
                }
            }
        }

        val terminal = best ?: return null
        val originPlace = RoutePlace("origin", originName, origin)
        val destinationPlace = RoutePlace("destination", destinationName, destination)
        val steps = reconstruct(terminal.state, previous, departureEpochSec, originPlace)
        if (steps.isEmpty()) return null

        val result = ArrayList<RouteLeg>(steps.size + 1)
        result += mergeRailSteps(steps)
        val beforeEgress = result.lastOrNull()?.arrivalEpochSec ?: departureEpochSec
        result += RouteLeg(
            mode = TransportMode.WALK,
            from = nodes[terminal.state.node].place(),
            to = destinationPlace,
            departureEpochSec = beforeEgress,
            arrivalEpochSec = beforeEgress + terminal.egress.seconds,
            walkMeters = terminal.egress.meters,
            uncertaintySeconds = 75,
            realtimeConfidence = 0.78
        )
        return RouteCandidate(
            id = buildRouteId(result),
            requestedDepartureEpochSec = departureEpochSec,
            legs = result
        )
    }

    private fun reconstruct(
        terminal: State,
        previous: Map<State, Previous>,
        departureEpochSec: Long,
        origin: RoutePlace
    ): List<RouteLeg> {
        val reversed = ArrayList<RouteLeg>()
        var state = terminal
        while (true) {
            when (val prev = previous[state]) {
                is Previous.Access -> {
                    reversed += RouteLeg(
                        mode = TransportMode.WALK,
                        from = origin,
                        to = nodes[state.node].place(),
                        departureEpochSec = departureEpochSec,
                        arrivalEpochSec = departureEpochSec + prev.walk.seconds,
                        walkMeters = prev.walk.meters,
                        uncertaintySeconds = 45,
                        realtimeConfidence = 0.90
                    )
                    break
                }
                is Previous.Ride -> {
                    val previousArrival = departureEpochSec + previousSeconds(prev.previous, previous)
                    val departure = previousArrival + prev.extraBeforeSeconds
                    reversed += RouteLeg(
                        mode = prev.edge.mode,
                        from = nodes[prev.edge.from].place(),
                        to = nodes[prev.edge.to].place(),
                        departureEpochSec = departure,
                        arrivalEpochSec = departure + prev.edge.seconds,
                        lineId = prev.edge.lineKey,
                        lineName = prev.edge.lineName,
                        waitSeconds = prev.extraBeforeSeconds,
                        uncertaintySeconds = maxOf(45, (prev.edge.seconds * (1.0 - prev.edge.confidence)).toInt()),
                        realtimeConfidence = prev.edge.confidence,
                        transferBufferSeconds = if (prev.previous.insideSystem) expectedWaitSeconds(prev.edge.mode) else 0
                    )
                    state = prev.previous
                }
                is Previous.Transfer -> {
                    val previousArrival = departureEpochSec + previousSeconds(prev.previous, previous)
                    reversed += RouteLeg(
                        mode = TransportMode.WALK,
                        from = nodes[prev.previous.node].place(),
                        to = nodes[state.node].place(),
                        departureEpochSec = previousArrival,
                        arrivalEpochSec = previousArrival + prev.seconds,
                        walkMeters = 0,
                        uncertaintySeconds = 60,
                        realtimeConfidence = 0.72
                    )
                    state = prev.previous
                }
                null -> return emptyList()
            }
        }
        reversed.reverse()

        // Rebase times sequentially. Dijkstra predecessor states contain correct costs, but a compact
        // sequential pass avoids exposing reconstruction bookkeeping as gaps or overlaps in UI.
        var cursor = departureEpochSec
        return reversed.map { leg ->
            val duration = leg.durationSeconds
            val gap = if (leg.mode == TransportMode.WALK) 0 else leg.waitSeconds
            val rebasedDeparture = cursor + gap
            val rebased = leg.copy(
                departureEpochSec = rebasedDeparture,
                arrivalEpochSec = rebasedDeparture + duration
            )
            cursor = rebased.arrivalEpochSec
            rebased
        }
    }

    private fun previousSeconds(state: State, previous: Map<State, Previous>): Long {
        var total = 0L
        var cursor = state
        while (true) {
            when (val prev = previous[cursor]) {
                is Previous.Access -> return total + prev.walk.seconds
                is Previous.Ride -> {
                    total += prev.extraBeforeSeconds + prev.edge.seconds
                    cursor = prev.previous
                }
                is Previous.Transfer -> {
                    total += prev.seconds
                    cursor = prev.previous
                }
                null -> return total
            }
        }
    }

    private fun mergeRailSteps(legs: List<RouteLeg>): List<RouteLeg> {
        if (legs.isEmpty()) return legs
        val result = ArrayList<RouteLeg>()
        var index = 0
        while (index < legs.size) {
            val first = legs[index]
            if (first.mode == TransportMode.WALK) {
                result += first
                index++
                continue
            }
            var last = first
            var cursor = index + 1
            while (cursor < legs.size) {
                val next = legs[cursor]
                if (next.mode != first.mode || next.lineId != first.lineId) break
                last = next
                cursor++
            }
            result += first.copy(
                to = last.to,
                arrivalEpochSec = last.arrivalEpochSec,
                uncertaintySeconds = legs.subList(index, cursor).sumOf { it.uncertaintySeconds }
            )
            index = cursor
        }
        return result
    }

    private fun relax(
        state: State,
        seconds: Int,
        prev: Previous,
        distance: MutableMap<State, Int>,
        previous: MutableMap<State, Previous>,
        queue: PriorityQueue<QueueItem>
    ) {
        val old = distance[state]
        if (old == null || seconds < old) {
            distance[state] = seconds
            previous[state] = prev
            queue += QueueItem(state, seconds)
        }
    }

    private fun walkingLinks(point: GeoPoint, towardDestination: Boolean): List<Access> {
        val candidates = nodes.asSequence()
            .map { it.index to haversineMeters(point, it.point) }
            .filter { it.second <= MAX_ACCESS_GEOMETRIC_METERS }
            .sortedBy { it.second }
            .take(MAX_ACCESS_CANDIDATES)
            .toList()

        val exact = ArrayList<Access>()
        for ((index, geometricMeters) in candidates) {
            val cost = walkGraph?.let { graph ->
                if (towardDestination) {
                    graph.shortestWalk(nodes[index].point, point, ACCESS_MAX_SECONDS, ACCESS_MAX_METERS)
                } else {
                    graph.shortestWalk(point, nodes[index].point, ACCESS_MAX_SECONDS, ACCESS_MAX_METERS)
                }
            } ?: RuntimeWalkGraph.WalkCost(
                seconds = ceil(geometricMeters * WALK_DETOUR_FACTOR / preferences.walkingSpeedMetersPerSecond).toInt(),
                meters = ceil(geometricMeters * WALK_DETOUR_FACTOR).toInt()
            )
            if (cost != null) exact += Access(index, cost)
        }
        return exact.sortedBy { it.cost.seconds }.take(MAX_EXACT_ACCESS)
    }

    private fun load(root: JSONObject) {
        val routes = root.getJSONArray("routes")
        for (routeIndex in 0 until routes.length()) {
            val route = routes.getJSONObject(routeIndex)
            if (!route.optBoolean("routeable", false)) continue
            val mode = when (route.optString("mode")) {
                "METRO" -> TransportMode.METRO
                "MCC" -> TransportMode.MCC
                // MCD requires a departure/headway feed before it is allowed into ETA routing.
                else -> continue
            }
            val routeId = route.getString("osm_relation_id")
            val lineKey = "${mode.name}:${route.optString("ref", routeId)}"
            val lineName = route.optString("ref").takeIf { it.isNotBlank() }
                ?: route.optString("name", mode.name)
            val confidence = route.optDouble("timing_confidence", 0.65).coerceIn(0.2, 0.95)
            val stops = route.getJSONArray("stops")
            val seconds = route.getJSONArray("segment_seconds")
            if (stops.length() < 2 || seconds.length() != stops.length() - 1) continue

            val local = IntArray(stops.length())
            for (i in 0 until stops.length()) {
                val stop = stops.getJSONObject(i)
                val osmId = stop.getString("osm_stop_id")
                val nodeIndex = nodeIndexByOsmId[osmId] ?: run {
                    val created = nodes.size
                    nodes += Node(
                        index = created,
                        osmId = osmId,
                        name = stop.optString("name", osmId),
                        point = GeoPoint(stop.getDouble("lat"), stop.getDouble("lon"))
                    )
                    nodeIndexByOsmId[osmId] = created
                    adjacency += ArrayList()
                    groupsByName.getOrPut(normalizeName(nodes[created].name)) { ArrayList() }.add(created)
                    created
                }
                local[i] = nodeIndex
                modesByNode.getOrPut(nodeIndex) { LinkedHashSet() }.add(mode)
                linesByNode.getOrPut(nodeIndex) { LinkedHashSet() }.add(lineKey)
            }
            for (i in 0 until seconds.length()) {
                val duration = seconds.getInt(i).coerceAtLeast(1)
                adjacency[local[i]] += Edge(
                    from = local[i],
                    to = local[i + 1],
                    seconds = duration,
                    routeId = routeId,
                    lineKey = lineKey,
                    lineName = lineName,
                    mode = mode,
                    confidence = confidence
                )
            }
        }
    }

    private fun transferSeconds(from: Int, to: Int): Int {
        val sameLine = linesByNode[from].orEmpty().any { it in linesByNode[to].orEmpty() }
        if (sameLine) return SAME_LINE_DIRECTION_CHANGE_SECONDS
        val fromMode = nodeMode(from)
        val toMode = nodeMode(to)
        return if (fromMode == TransportMode.MCC || toMode == TransportMode.MCC) {
            MCC_TRANSFER_SECONDS
        } else {
            METRO_TRANSFER_SECONDS
        }
    }

    private fun nodeMode(index: Int): TransportMode =
        modesByNode[index]?.firstOrNull() ?: TransportMode.METRO

    private fun expectedWaitSeconds(mode: TransportMode): Int = when (mode) {
        TransportMode.METRO -> METRO_EXPECTED_WAIT_SECONDS
        TransportMode.MCC -> MCC_EXPECTED_WAIT_SECONDS
        else -> 0
    }

    private fun entranceSeconds(mode: TransportMode): Int = when (mode) {
        TransportMode.METRO -> METRO_ENTRANCE_SECONDS
        TransportMode.MCC -> MCC_ENTRANCE_SECONDS
        else -> 0
    }

    private fun exitSeconds(mode: TransportMode): Int = when (mode) {
        TransportMode.METRO -> METRO_EXIT_SECONDS
        TransportMode.MCC -> MCC_EXIT_SECONDS
        else -> 0
    }

    private fun Node.place(): RoutePlace = RoutePlace("rail:$osmId", name, point)

    private fun buildRouteId(legs: List<RouteLeg>): String {
        val signature = legs.joinToString("|") {
            "${it.mode}:${it.lineId ?: "walk"}:${it.from.id}:${it.to.id}"
        }
        return "rail-${signature.hashCode().toUInt().toString(16)}"
    }

    private fun normalizeName(value: String): String = value
        .lowercase()
        .replace('ё', 'е')
        .replace(Regex("[^а-яa-z0-9]+"), "")

    private fun haversineMeters(a: GeoPoint, b: GeoPoint): Double {
        val p1 = a.lat * PI / 180.0
        val p2 = b.lat * PI / 180.0
        val dLat = (b.lat - a.lat) * PI / 180.0
        val dLon = (b.lon - a.lon) * PI / 180.0
        val q = sin(dLat / 2) * sin(dLat / 2) + cos(p1) * cos(p2) * sin(dLon / 2) * sin(dLon / 2)
        return 2.0 * EARTH_RADIUS_METERS * asin(min(1.0, sqrt(q)))
    }

    companion object {
        private const val EARTH_RADIUS_METERS = 6_371_000.0
        private const val WALK_DETOUR_FACTOR = 1.20
        private const val MAX_ACCESS_GEOMETRIC_METERS = 2_400
        private const val ACCESS_MAX_METERS = 3_000
        private const val ACCESS_MAX_SECONDS = 40 * 60
        private const val MAX_ACCESS_CANDIDATES = 10
        private const val MAX_EXACT_ACCESS = 5

        // Conservative expected values until live/headway data is available. Their uncertainty is
        // carried into RouteLeg, so ranking does not treat them as realtime truth.
        private const val METRO_EXPECTED_WAIT_SECONDS = 120
        private const val MCC_EXPECTED_WAIT_SECONDS = 240
        private const val METRO_ENTRANCE_SECONDS = 90
        private const val MCC_ENTRANCE_SECONDS = 75
        private const val METRO_EXIT_SECONDS = 75
        private const val MCC_EXIT_SECONDS = 60
        private const val METRO_TRANSFER_SECONDS = 180
        private const val MCC_TRANSFER_SECONDS = 240
        private const val SAME_LINE_DIRECTION_CHANGE_SECONDS = 60
        private const val SAME_PLATFORM_CHANGE_SECONDS = 45

        fun openOrNull(
            runtimeRoot: File,
            preferences: RoutePreferences,
            walkGraph: RuntimeWalkGraph?
        ): RailGraphRouter? {
            val file = File(runtimeRoot, "rail/graph.json")
            if (!file.exists()) return null
            return runCatching { RailGraphRouter(preferences, walkGraph, file) }.getOrNull()
        }
    }
}
